from django.core.exceptions import ValidationError


def validate_bid(value):
    pass
